-- 사진 원본은 Storage photos 버킷에 유지하고, Table Editor에서 업무별로 찾을 수 있게 색인을 만듭니다.
-- 기존 카카오 앨범 링크를 유지하기 위해 기존 파일 경로는 절대 이동하거나 삭제하지 않습니다.

alter table public.photo_albums
  add column if not exists category text not null default '기존 미분류',
  add column if not exists author text,
  add column if not exists region text,
  add column if not exists source_type text not null default 'legacy';

create table if not exists public.photo_assets (
  id bigint generated by default as identity primary key,
  album_id uuid not null references public.photo_albums(id) on delete cascade,
  public_url text not null,
  storage_path text not null,
  file_name text,
  mime_type text,
  sort_order integer not null default 1,
  created_at timestamptz not null default now(),
  unique(album_id, public_url)
);

alter table public.photo_assets
  add column if not exists organized_path text,
  add column if not exists archived_at timestamptz,
  add column if not exists archive_error text;

alter table public.photo_assets enable row level security;
drop policy if exists "photo assets anon read" on public.photo_assets;
drop policy if exists "photo assets anon insert" on public.photo_assets;
create policy "photo assets anon read" on public.photo_assets for select to anon using (true);
create policy "photo assets anon insert" on public.photo_assets for insert to anon with check (true);
grant select, insert on public.photo_assets to anon;

-- 기존 모든 앨범의 URL을 파일별 목록으로 생성합니다.
insert into public.photo_assets (album_id, public_url, storage_path, file_name, sort_order)
select
  a.id,
  item.url,
  regexp_replace(item.url, '^.*/photos/', ''),
  regexp_replace(regexp_replace(item.url, '\\?.*$', ''), '^.*/', ''),
  item.ordinality::integer
from public.photo_albums a
cross join lateral jsonb_array_elements_text(to_jsonb(a.urls)) with ordinality as item(url, ordinality)
on conflict (album_id, public_url) do update set
  storage_path = excluded.storage_path,
  file_name = excluded.file_name,
  sort_order = excluded.sort_order;

-- 원문에 앨범 링크가 남아 있는 점검/AS/확장성 기록에서 기존 앨범 분류를 복원합니다.
update public.photo_albums a
set category = '점검', source_type = 'inspection', vendor = coalesce(nullif(a.vendor, ''), j."_업체명")
from public.jeomgeom j
where position(a.id::text in coalesce(j."_원문", '')) > 0
  and a.source_type in ('legacy', 'field');

update public.photo_albums a
set category = 'AS', source_type = 'as', vendor = coalesce(nullif(a.vendor, ''), r."_업체명")
from public.as_records r
where position(a.id::text in coalesce(r."_원문", '')) > 0
  and a.source_type in ('legacy', 'field');

update public.photo_albums a
set category = '확장성 IT', source_type = 'expansion_it', vendor = coalesce(nullif(a.vendor, ''), p."_업체명")
from public.pc_expansion p
where position(a.id::text in coalesce(p."_원문", '')) > 0
  and a.source_type in ('legacy', 'field');

update public.photo_albums a
set category = '확장성 복합기', source_type = 'expansion_copier', vendor = coalesce(nullif(a.vendor, ''), m."_업체명")
from public.mfp_expansion m
where position(a.id::text in coalesce(m."_원문", '')) > 0
  and a.source_type in ('legacy', 'field');

-- 담당자 변경·불만 등 FIELD 시트 동기화 작업도 원문 링크를 이용해 복원합니다.
update public.photo_albums a
set
  category = case j.category
    when 'contact_change' then '담당자/주소 변경'
    when 'complaint' then '불만'
    when 'expansion_it' then '확장성 IT'
    when 'expansion_copier' then '확장성 복합기'
    else a.category
  end,
  source_type = coalesce(j.category, a.source_type),
  vendor = coalesce(nullif(a.vendor, ''), j.vendor),
  author = coalesce(nullif(a.author, ''), j.author),
  region = coalesce(nullif(a.region, ''), j.region)
from public.field_sheet_sync_jobs j
where position(a.id::text in coalesce(j.source_text, '')) > 0;

create index if not exists photo_assets_album_idx on public.photo_assets(album_id, sort_order);
create index if not exists photo_assets_path_idx on public.photo_assets(storage_path);
create index if not exists photo_assets_organized_idx on public.photo_assets(organized_path) where organized_path is not null;
create index if not exists photo_albums_category_created_idx on public.photo_albums(category, created_at desc);
create index if not exists photo_albums_vendor_created_idx on public.photo_albums(vendor, created_at desc);
