-- Supabase SQL Editor에서 1회 실행: 일일업무/주간현황판
create extension if not exists pgcrypto;

create table if not exists public.visit_logs (
  id uuid primary key default gen_random_uuid(),
  work_date date not null,
  author text not null,
  vendor text not null,
  visited boolean not null default true,
  arrival_time time,
  machine_count integer not null default 0 check (machine_count >= 0),
  grade text,
  contract_ended boolean not null default false,
  work_kinds text[] not null default '{}',
  minutes jsonb not null default '{}'::jsonb,
  sales_it text,
  sales_copier text,
  commute text,
  note text,
  "_dupKey" text not null unique,
  created_at timestamptz not null default now()
);
alter table public.visit_logs add column if not exists work_kinds text[] not null default '{}';
alter table public.visit_logs add column if not exists grade text;
alter table public.visit_logs add column if not exists contract_ended boolean not null default false;
alter table public.visit_logs add column if not exists source_text text;
create index if not exists visit_logs_author_date_idx on public.visit_logs(author, work_date desc);

create table if not exists public.weekly_notes (
  id uuid primary key default gen_random_uuid(),
  author text not null,
  week_start date not null,
  goals jsonb not null default '{}'::jsonb,
  goal_items jsonb not null default '[]'::jsonb,
  bottlenecks jsonb not null default '[]'::jsonb,
  this_week_goal text not null default '', this_week_result text not null default '', next_week_goal text not null default '',
  review text not null default '', growth text not null default '', challenge text not null default '',
  special text not null default '', learning text not null default '', request text not null default '', praise text not null default '',
  updated_at timestamptz not null default now(),
  unique(author, week_start)
);
alter table public.weekly_notes add column if not exists goal_items jsonb not null default '[]'::jsonb;
alter table public.weekly_notes add column if not exists bottlenecks jsonb not null default '[]'::jsonb;
alter table public.weekly_notes add column if not exists this_week_goal text not null default '';
alter table public.weekly_notes add column if not exists this_week_result text not null default '';
alter table public.weekly_notes add column if not exists next_week_goal text not null default '';

create table if not exists public.office_logs (
  id uuid primary key default gen_random_uuid(),
  work_date date not null,
  author text not null,
  return_time time,
  values jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique(author, work_date)
);

create table if not exists public.quarterly_plans (
  id uuid primary key default gen_random_uuid(), author text not null, year integer not null, quarter integer not null check (quarter between 1 and 4),
  goals jsonb not null default '[]'::jsonb, updated_at timestamptz not null default now(), unique(author, year, quarter)
);
create table if not exists public.golden_cards (
  id uuid primary key default gen_random_uuid(), author text not null, year integer not null, quarter integer not null check (quarter between 1 and 4),
  answers jsonb not null default '{}'::jsonb, updated_at timestamptz not null default now(), unique(author, year, quarter)
);
create table if not exists public.logistics_records (
  id bigint generated by default as identity primary key,
  "작성일" date, "작성자" text, "구분" text, "거래처명" text, "품목" text, "수량" text,
  "소모품(납품/청구여부)" text, "셋팅여부" text, "이메일카운터셋팅완료" text, "한조셋팅완료" text,
  "상태체크(내부/외부)" text, "여분토너체크(철수 시)" text, "특이사항" text,
  "_업체명" text, "_원문" text, "_출처" text, "_dupKey" text not null unique, created_at timestamptz not null default now()
);

create table if not exists public.happycall_messages (
  id uuid primary key default gen_random_uuid(),
  visit_id uuid not null unique references public.visit_logs(id) on delete cascade,
  author text not null,
  recipient text not null default '',
  keyman text not null default '',
  message text not null default '',
  status text not null default 'pending' check (status in ('pending', 'sent', 'failed', 'skip')),
  sent_at timestamptz,
  error text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.promo_materials (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  category text not null,
  description text not null default '',
  file_url text not null,
  file_type text not null default 'application/pdf',
  active boolean not null default true,
  created_by text not null,
  "_dupKey" text not null unique,
  created_at timestamptz not null default now()
);

insert into storage.buckets (id, name, public)
values ('promo-materials', 'promo-materials', true)
on conflict (id) do update set public = true;

create table if not exists public.misu (
  id bigint generated by default as identity primary key,
  "입력일" text, "작성자" text, "지역" text, "업체명" text, "담당자" text, "등급" text,
  "미수금액" text, "보증금미입금" text, "미수개월" text,
  "방문내용" text, "고객반응" text, "약속일" text, "후속담당자" text, "특이사항" text,
  "_업체명" text, "_원문" text, "_출처" text, "_dupKey" text not null unique, created_at timestamptz not null default now()
);

create table if not exists public.bulman (
  id bigint generated by default as identity primary key,
  "작성자" text, "지역" text, "등급" text, "업체명" text, "담당자" text, "기종" text,
  "불만유형" text, "불만정도" text, "불편내용" text, "고객요청사항" text,
  "방문일" text, "처리자" text, "조치내용" text, "현장고객반응" text,
  "외부원인" text, "내부원인" text, "실행방향" text, "제시선택지" text, "내부협의" text,
  "후속담당자" text, "기한" text, "다음확인일" text, "최종상태" text, "재발방지" text,
  "_업체명" text, "_원문" text, "_출처" text, "_dupKey" text not null unique, created_at timestamptz not null default now()
);

create table if not exists public.recontract (
  id bigint generated by default as identity primary key,
  "작성자" text, "지역" text, "등급" text, "업체명" text, "담당자" text, "기종" text, "계약종료일" text,
  "갱신상태" text, "갱신위험도" text, "고객반응현황" text, "불편요구" text, "업무변화" text, "타사비교" text,
  "월렌탈료" text, "사용량초과" text, "기존혜택" text,
  "제안일자" text, "제안조건" text, "설명내용" text, "제안고객반응" text,
  "외부원인" text, "내부원인" text, "갱신방향" text, "제시선택지" text, "내부협의" text,
  "후속담당자" text, "기한" text, "다음확인일" text, "최종상태" text, "관리포인트" text,
  "_업체명" text, "_원문" text, "_출처" text, "_dupKey" text not null unique, created_at timestamptz not null default now()
);

create table if not exists public.overage_adjust (
  id bigint generated by default as identity primary key,
  "방문일" text, "작성자" text, "지역" text, "업체명" text, "담당자" text, "기종" text,
  "현재조건" text, "누적결과" text, "제안" text, "고객반응" text, "할인조건변경" text, "진행상태" text,
  "_업체명" text, "_원문" text, "_출처" text, "_dupKey" text not null unique, created_at timestamptz not null default now()
);

create table if not exists public.pc_expansion (
  id bigint generated by default as identity primary key,
  "날짜" date, "작성자" text, "등급" text, "사무/설계/디자인/개발" text, "세부사양" text, "지역" text,
  "업체담당자" text, "연락처" text, "IT담당자" text, "렌탈or구매or유지보수" text,
  "지정업체" text, "지정업체만족도" text, "총 인원" text, "인원 추가 설명" text,
  "수량" text, "금액" text, "시기" text, "시기 추가 설명" text, "어필 OR 추가영업" text,
  "_업체명" text, "_원문" text, "_출처" text, "_dupKey" text not null unique, created_at timestamptz not null default now()
);

create table if not exists public.copier_expansion (
  id bigint generated by default as identity primary key,
  "등록일" date, "등록자" text, "전략영업담당자" text, "상호명" text, "업종및인원매출" text,
  "실제미팅주소" text, "프로젝트진행상황" text, "성함및직함" text, "연락처" text, "의사결정파급력" text,
  "개인히스토리" text, "품목원문" text, "예상발주금액만원" text, "예상발주시기" text,
  "계약종료예정일" text, "특이사항미팅내용" text, "관리등급" text,
  "_업체명" text, "_원문" text, "_출처" text, "_dupKey" text not null unique, created_at timestamptz not null default now()
);

alter table public.misu add column if not exists "입력일" text;
alter table public.misu add column if not exists "작성자" text;
alter table public.misu add column if not exists "지역" text;
alter table public.misu add column if not exists "업체명" text;
alter table public.misu add column if not exists "담당자" text;
alter table public.misu add column if not exists "등급" text;
alter table public.misu add column if not exists "미수금액" text;
alter table public.misu add column if not exists "보증금미입금" text;
alter table public.misu add column if not exists "미수개월" text;
alter table public.misu add column if not exists "방문내용" text;
alter table public.misu add column if not exists "고객반응" text;
alter table public.misu add column if not exists "약속일" text;
alter table public.misu add column if not exists "후속담당자" text;
alter table public.misu add column if not exists "특이사항" text;
alter table public.misu add column if not exists "_업체명" text;
alter table public.misu add column if not exists "_원문" text;
alter table public.misu add column if not exists "_출처" text;
alter table public.misu add column if not exists "_dupKey" text;

alter table public.bulman add column if not exists "작성자" text;
alter table public.bulman add column if not exists "지역" text;
alter table public.bulman add column if not exists "등급" text;
alter table public.bulman add column if not exists "업체명" text;
alter table public.bulman add column if not exists "담당자" text;
alter table public.bulman add column if not exists "기종" text;
alter table public.bulman add column if not exists "불만유형" text;
alter table public.bulman add column if not exists "불만정도" text;
alter table public.bulman add column if not exists "불편내용" text;
alter table public.bulman add column if not exists "고객요청사항" text;
alter table public.bulman add column if not exists "방문일" text;
alter table public.bulman add column if not exists "처리자" text;
alter table public.bulman add column if not exists "조치내용" text;
alter table public.bulman add column if not exists "현장고객반응" text;
alter table public.bulman add column if not exists "외부원인" text;
alter table public.bulman add column if not exists "내부원인" text;
alter table public.bulman add column if not exists "실행방향" text;
alter table public.bulman add column if not exists "제시선택지" text;
alter table public.bulman add column if not exists "내부협의" text;
alter table public.bulman add column if not exists "후속담당자" text;
alter table public.bulman add column if not exists "기한" text;
alter table public.bulman add column if not exists "다음확인일" text;
alter table public.bulman add column if not exists "최종상태" text;
alter table public.bulman add column if not exists "재발방지" text;
alter table public.bulman add column if not exists "_업체명" text;
alter table public.bulman add column if not exists "_원문" text;
alter table public.bulman add column if not exists "_출처" text;
alter table public.bulman add column if not exists "_dupKey" text;

alter table public.recontract add column if not exists "작성자" text;
alter table public.recontract add column if not exists "지역" text;
alter table public.recontract add column if not exists "등급" text;
alter table public.recontract add column if not exists "업체명" text;
alter table public.recontract add column if not exists "담당자" text;
alter table public.recontract add column if not exists "기종" text;
alter table public.recontract add column if not exists "계약종료일" text;
alter table public.recontract add column if not exists "갱신상태" text;
alter table public.recontract add column if not exists "갱신위험도" text;
alter table public.recontract add column if not exists "고객반응현황" text;
alter table public.recontract add column if not exists "불편요구" text;
alter table public.recontract add column if not exists "업무변화" text;
alter table public.recontract add column if not exists "타사비교" text;
alter table public.recontract add column if not exists "월렌탈료" text;
alter table public.recontract add column if not exists "사용량초과" text;
alter table public.recontract add column if not exists "기존혜택" text;
alter table public.recontract add column if not exists "제안일자" text;
alter table public.recontract add column if not exists "제안조건" text;
alter table public.recontract add column if not exists "설명내용" text;
alter table public.recontract add column if not exists "제안고객반응" text;
alter table public.recontract add column if not exists "외부원인" text;
alter table public.recontract add column if not exists "내부원인" text;
alter table public.recontract add column if not exists "갱신방향" text;
alter table public.recontract add column if not exists "제시선택지" text;
alter table public.recontract add column if not exists "내부협의" text;
alter table public.recontract add column if not exists "후속담당자" text;
alter table public.recontract add column if not exists "기한" text;
alter table public.recontract add column if not exists "다음확인일" text;
alter table public.recontract add column if not exists "최종상태" text;
alter table public.recontract add column if not exists "관리포인트" text;
alter table public.recontract add column if not exists "_업체명" text;
alter table public.recontract add column if not exists "_원문" text;
alter table public.recontract add column if not exists "_출처" text;
alter table public.recontract add column if not exists "_dupKey" text;

alter table public.overage_adjust add column if not exists "방문일" text;
alter table public.overage_adjust add column if not exists "작성자" text;
alter table public.overage_adjust add column if not exists "지역" text;
alter table public.overage_adjust add column if not exists "업체명" text;
alter table public.overage_adjust add column if not exists "담당자" text;
alter table public.overage_adjust add column if not exists "기종" text;
alter table public.overage_adjust add column if not exists "현재조건" text;
alter table public.overage_adjust add column if not exists "누적결과" text;
alter table public.overage_adjust add column if not exists "제안" text;
alter table public.overage_adjust add column if not exists "고객반응" text;
alter table public.overage_adjust add column if not exists "할인조건변경" text;
alter table public.overage_adjust add column if not exists "진행상태" text;
alter table public.overage_adjust add column if not exists "_업체명" text;
alter table public.overage_adjust add column if not exists "_원문" text;
alter table public.overage_adjust add column if not exists "_출처" text;
alter table public.overage_adjust add column if not exists "_dupKey" text;

alter table public.pc_expansion add column if not exists "날짜" text;
alter table public.pc_expansion add column if not exists "작성자" text;
alter table public.pc_expansion add column if not exists "등급" text;
alter table public.pc_expansion add column if not exists "사무/설계/디자인/개발" text;
alter table public.pc_expansion add column if not exists "세부사양" text;
alter table public.pc_expansion add column if not exists "지역" text;
alter table public.pc_expansion add column if not exists "업체담당자" text;
alter table public.pc_expansion add column if not exists "연락처" text;
alter table public.pc_expansion add column if not exists "IT담당자" text;
alter table public.pc_expansion add column if not exists "렌탈or구매or유지보수" text;
alter table public.pc_expansion add column if not exists "지정업체" text;
alter table public.pc_expansion add column if not exists "지정업체만족도" text;
alter table public.pc_expansion add column if not exists "총 인원" text;
alter table public.pc_expansion add column if not exists "인원 추가 설명" text;
alter table public.pc_expansion add column if not exists "수량" text;
alter table public.pc_expansion add column if not exists "금액" text;
alter table public.pc_expansion add column if not exists "시기" text;
alter table public.pc_expansion add column if not exists "시기 추가 설명" text;
alter table public.pc_expansion add column if not exists "어필 OR 추가영업" text;
alter table public.pc_expansion add column if not exists "_업체명" text;
alter table public.pc_expansion add column if not exists "_원문" text;
alter table public.pc_expansion add column if not exists "_출처" text;
alter table public.pc_expansion add column if not exists "_dupKey" text;

alter table public.copier_expansion add column if not exists "등록일" text;
alter table public.copier_expansion add column if not exists "등록자" text;
alter table public.copier_expansion add column if not exists "전략영업담당자" text;
alter table public.copier_expansion add column if not exists "상호명" text;
alter table public.copier_expansion add column if not exists "업종및인원매출" text;
alter table public.copier_expansion add column if not exists "실제미팅주소" text;
alter table public.copier_expansion add column if not exists "프로젝트진행상황" text;
alter table public.copier_expansion add column if not exists "성함및직함" text;
alter table public.copier_expansion add column if not exists "연락처" text;
alter table public.copier_expansion add column if not exists "의사결정파급력" text;
alter table public.copier_expansion add column if not exists "개인히스토리" text;
alter table public.copier_expansion add column if not exists "품목원문" text;
alter table public.copier_expansion add column if not exists "예상발주금액만원" text;
alter table public.copier_expansion add column if not exists "예상발주시기" text;
alter table public.copier_expansion add column if not exists "계약종료예정일" text;
alter table public.copier_expansion add column if not exists "특이사항미팅내용" text;
alter table public.copier_expansion add column if not exists "관리등급" text;
alter table public.copier_expansion add column if not exists "_업체명" text;
alter table public.copier_expansion add column if not exists "_원문" text;
alter table public.copier_expansion add column if not exists "_출처" text;
alter table public.copier_expansion add column if not exists "_dupKey" text;

create unique index if not exists misu_dupkey_idx on public.misu("_dupKey");
create unique index if not exists bulman_dupkey_idx on public.bulman("_dupKey");
create unique index if not exists recontract_dupkey_idx on public.recontract("_dupKey");
create unique index if not exists overage_adjust_dupkey_idx on public.overage_adjust("_dupKey");
create unique index if not exists pc_expansion_dupkey_idx on public.pc_expansion("_dupKey");
create unique index if not exists copier_expansion_dupkey_idx on public.copier_expansion("_dupKey");

alter table public.visit_logs enable row level security;
alter table public.weekly_notes enable row level security;
alter table public.office_logs enable row level security;
alter table public.quarterly_plans enable row level security;
alter table public.golden_cards enable row level security;
alter table public.happycall_messages enable row level security;
alter table public.promo_materials enable row level security;
alter table public.logistics_records enable row level security;
alter table public.misu enable row level security;
alter table public.bulman enable row level security;
alter table public.recontract enable row level security;
alter table public.overage_adjust enable row level security;
alter table public.pc_expansion enable row level security;
alter table public.copier_expansion enable row level security;
-- 현재 앱이 anon 기반이므로 기존 운영 방식과 맞춘 정책. 직원 로그인 도입 시 auth.uid() 기반으로 교체한다.
drop policy if exists "visit_logs anon read" on public.visit_logs;
drop policy if exists "visit_logs anon insert" on public.visit_logs;
drop policy if exists "weekly_notes anon all" on public.weekly_notes;
drop policy if exists "office_logs anon all" on public.office_logs;
drop policy if exists "quarterly_plans anon all" on public.quarterly_plans;
drop policy if exists "golden_cards anon all" on public.golden_cards;
drop policy if exists "happycall_messages anon all" on public.happycall_messages;
drop policy if exists "promo_materials anon all" on public.promo_materials;
drop policy if exists "promo materials anon read" on storage.objects;
drop policy if exists "promo materials anon insert" on storage.objects;
drop policy if exists "logistics_records anon all" on public.logistics_records;
drop policy if exists "logistics_records anon read" on public.logistics_records;
drop policy if exists "logistics_records anon insert" on public.logistics_records;
drop policy if exists "misu anon read" on public.misu;
drop policy if exists "misu anon insert" on public.misu;
drop policy if exists "bulman anon read" on public.bulman;
drop policy if exists "bulman anon insert" on public.bulman;
drop policy if exists "recontract anon read" on public.recontract;
drop policy if exists "recontract anon insert" on public.recontract;
drop policy if exists "overage_adjust anon read" on public.overage_adjust;
drop policy if exists "overage_adjust anon insert" on public.overage_adjust;
drop policy if exists "pc_expansion anon read" on public.pc_expansion;
drop policy if exists "pc_expansion anon insert" on public.pc_expansion;
drop policy if exists "copier_expansion anon read" on public.copier_expansion;
drop policy if exists "copier_expansion anon insert" on public.copier_expansion;
create policy "visit_logs anon read" on public.visit_logs for select to anon using (true);
create policy "visit_logs anon insert" on public.visit_logs for insert to anon with check (true);
create policy "weekly_notes anon all" on public.weekly_notes for all to anon using (true) with check (true);
create policy "office_logs anon all" on public.office_logs for all to anon using (true) with check (true);
create policy "quarterly_plans anon all" on public.quarterly_plans for all to anon using (true) with check (true);
create policy "golden_cards anon all" on public.golden_cards for all to anon using (true) with check (true);
create policy "happycall_messages anon all" on public.happycall_messages for all to anon using (true) with check (true);
create policy "promo_materials anon all" on public.promo_materials for all to anon using (true) with check (true);
create policy "promo materials anon read" on storage.objects for select to anon using (bucket_id = 'promo-materials');
create policy "promo materials anon insert" on storage.objects for insert to anon with check (bucket_id = 'promo-materials');
create policy "logistics_records anon read" on public.logistics_records for select to anon using (true);
create policy "logistics_records anon insert" on public.logistics_records for insert to anon with check (true);
create policy "misu anon read" on public.misu for select to anon using (true);
create policy "misu anon insert" on public.misu for insert to anon with check (true);
create policy "bulman anon read" on public.bulman for select to anon using (true);
create policy "bulman anon insert" on public.bulman for insert to anon with check (true);
create policy "recontract anon read" on public.recontract for select to anon using (true);
create policy "recontract anon insert" on public.recontract for insert to anon with check (true);
create policy "overage_adjust anon read" on public.overage_adjust for select to anon using (true);
create policy "overage_adjust anon insert" on public.overage_adjust for insert to anon with check (true);
create policy "pc_expansion anon read" on public.pc_expansion for select to anon using (true);
create policy "pc_expansion anon insert" on public.pc_expansion for insert to anon with check (true);
create policy "copier_expansion anon read" on public.copier_expansion for select to anon using (true);
create policy "copier_expansion anon insert" on public.copier_expansion for insert to anon with check (true);
grant select, insert on public.visit_logs to anon;
grant select, insert, update on public.weekly_notes to anon;
grant select, insert, update on public.office_logs to anon;
grant select, insert, update on public.quarterly_plans to anon;
grant select, insert, update on public.golden_cards to anon;
grant select, insert, update on public.happycall_messages to anon;
grant select, insert, update on public.promo_materials to anon;
grant select, insert on public.logistics_records to anon;
grant select, insert on public.misu to anon;
grant select, insert on public.bulman to anon;
grant select, insert on public.recontract to anon;
grant select, insert on public.overage_adjust to anon;
grant select, insert on public.pc_expansion to anon;
grant select, insert on public.copier_expansion to anon;
