import { useEffect, useMemo, useState } from "react";
import { AUTHOR_BOOK, AUTHOR_TEAMS } from "./authors";
import {
  GOLDEN_CATEGORIES, GOLDEN_QUESTIONS, getGoldenCard, getQuarterlyPlan, getWeeklyNotes, saveGoldenCard,
  saveQuarterlyPlan, type GoldenCard, type LevelGoal, type QuarterlyPlan, type WeeklyNoteRow,
} from "./visits";

type Tab = "records" | "plan" | "golden";
const types = [["growth", "성장노트", "💡"], ["learning", "배운 점", "🧡"], ["challenge", "아이디어", "🎯"], ["special", "특이사항", "📌"]] as const;
const pad = (n: number) => String(n).padStart(2, "0");
function quarterRange(year: number, quarter: number) { const m = (quarter - 1) * 3 + 1; const end = new Date(year, m + 2, 0).getDate(); return { start: `${year}-${pad(m)}-01`, end: `${year}-${pad(m + 2)}-${pad(end)}` }; }

export default function GrowthHub({ author }: { author: string }) {
  const now = new Date();
  const [tab, setTab] = useState<Tab>("records");
  const [year, setYear] = useState(now.getFullYear());
  const [quarter, setQuarter] = useState(Math.floor(now.getMonth() / 3) + 1);
  const [recordPeriod, setRecordPeriod] = useState<"month" | "quarter" | "year">("quarter");
  const [recordMonth, setRecordMonth] = useState(now.getMonth() + 1);
  const [person, setPerson] = useState(author);
  const [type, setType] = useState("all");
  const [query, setQuery] = useState("");
  const [notes, setNotes] = useState<WeeklyNoteRow[]>([]);
  const [plan, setPlan] = useState<QuarterlyPlan>({ author, year, quarter, goals: [] });
  const [card, setCard] = useState<GoldenCard>({ author, year, quarter, answers: {} });
  const [question, setQuestion] = useState(0);
  const [expanded, setExpanded] = useState("");
  const [message, setMessage] = useState("");
  const [loading, setLoading] = useState(true);
  const qRange = quarterRange(year, quarter);
  const monthEnd = new Date(year, recordMonth, 0).getDate();
  const range = tab === "records" && recordPeriod === "year" ? { start: `${year}-01-01`, end: `${year}-12-31` }
    : tab === "records" && recordPeriod === "month" ? { start: `${year}-${pad(recordMonth)}-01`, end: `${year}-${pad(recordMonth)}-${pad(monthEnd)}` } : qRange;
  useEffect(() => {
    let alive = true;
    Promise.all([getWeeklyNotes(range.start, range.end), person ? getQuarterlyPlan(person, year, quarter) : Promise.resolve({ author: "", year, quarter, goals: [] }), person ? getGoldenCard(person, year, quarter) : Promise.resolve({ author: "", year, quarter, answers: {} })])
      .then(([n, p, c]) => { if (alive) { setNotes(n); setPlan(p); setCard(c); } })
      .catch((e) => { if (alive) setMessage((e as Error).message); })
      .finally(() => { if (alive) setLoading(false); });
    return () => { alive = false; };
  }, [person, year, quarter, range.start, range.end]);

  const entries = useMemo(() => notes.flatMap((n) => types.map(([key, label, icon]) => ({ id: `${n.author}-${n.weekStart}-${key}`, author: n.author, week: n.weekStart, key, label, icon, text: n[key] })).filter((e) => e.text.trim())).filter((e) => (person ? e.author === person : true) && (type === "all" || e.key === type) && (!query.trim() || `${e.author} ${e.text}`.toLowerCase().includes(query.trim().toLowerCase()))), [notes, person, type, query]);

  const addGoal = () => { const g: LevelGoal = { id: crypto.randomUUID(), category: "자기개발", title: "", currentLevel: "", targetLevel: "", budget: "", month1: "", month2: "", month3: "", progress: 0 }; setPlan({ ...plan, author: person, year, quarter, goals: [...plan.goals, g] }); };
  const setGoal = (id: string, patch: Partial<LevelGoal>) => setPlan({ ...plan, goals: plan.goals.map((g) => g.id === id ? { ...g, ...patch } : g) });
  const savePlan = async () => { try { await saveQuarterlyPlan({ ...plan, author: person, year, quarter }); setMessage("레벨업계획을 저장했습니다."); } catch (e) { setMessage((e as Error).message); } };
  const answer = (q: string, cat: string) => card.answers[q]?.[cat] || "";
  const setAnswer = (q: string, cat: string, value: string) => setCard({ ...card, answers: { ...card.answers, [q]: { ...(card.answers[q] || {}), [cat]: value } } });
  const saveCard = async () => { try { await saveGoldenCard({ ...card, author: person, year, quarter }); setMessage("골든미팅카드를 저장했습니다."); } catch (e) { setMessage((e as Error).message); } };

  return <div className="space-y-5 pb-16">
    <section className="rounded-3xl bg-gradient-to-br from-[#172033] to-[#263653] p-6 text-white shadow-xl lg:p-8"><div className="text-sm font-semibold text-amber-300">성장의 기록이 분기의 성과가 되도록</div><h2 className="mt-2 text-3xl font-extrabold lg:text-4xl">성장기록 허브</h2><p className="mt-2 max-w-2xl text-sm leading-relaxed text-slate-300">주간 성장노트·배운 점·아이디어를 모아보고, 그 근거로 레벨업계획과 골든미팅카드를 작성합니다.</p></section>
    <section className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm xl:flex-row xl:items-center xl:justify-between"><div className="grid grid-cols-3 gap-1 rounded-xl bg-slate-100 p-1">{([['records','성장기록 모아보기'],['plan','레벨업계획'],['golden','골든미팅카드']] as [Tab,string][]).map(([k,l]) => <button key={k} onClick={() => setTab(k)} className={`rounded-lg px-5 py-2.5 text-sm font-bold ${tab === k ? "bg-white text-slate-900 shadow-sm" : "text-slate-400"}`}>{l}</button>)}</div><div className="flex flex-wrap gap-2"><select value={year} onChange={(e) => setYear(Number(e.target.value))} className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold">{Array.from({ length: 6 }, (_, i) => now.getFullYear() - 4 + i).map((y) => <option key={y}>{y}</option>)}</select><div className="flex gap-1">{[1,2,3,4].map((q) => <button key={q} onClick={() => setQuarter(q)} className={`rounded-xl px-3 py-2 text-sm font-bold ${quarter === q ? "bg-slate-800 text-white" : "border border-slate-200 text-slate-500"}`}>{q}Q</button>)}</div><select value={person} onChange={(e) => setPerson(e.target.value)} className="rounded-xl border border-slate-200 px-4 py-2 text-sm"><option value="">전 직원</option>{AUTHOR_TEAMS.map((t) => <optgroup key={t} label={`${t}팀`}>{AUTHOR_BOOK[t].map((a) => <option key={a}>{a}</option>)}</optgroup>)}</select></div></section>
    {tab === "records" && <section className="flex flex-wrap items-center gap-2 rounded-2xl border border-slate-200 bg-white p-3"><span className="mr-2 text-xs font-bold text-slate-400">조회 범위</span>{([['month','월별'],['quarter','분기'],['year','연간']] as const).map(([k,l])=><button key={k} onClick={()=>setRecordPeriod(k)} className={`rounded-lg px-3 py-2 text-xs font-bold ${recordPeriod===k?"bg-blue-600 text-white":"bg-slate-100 text-slate-500"}`}>{l}</button>)}{recordPeriod==='month'&&<select value={recordMonth} onChange={(e)=>setRecordMonth(Number(e.target.value))} className="rounded-lg border border-slate-200 px-3 py-2 text-xs">{Array.from({length:12},(_,i)=>i+1).map((m)=><option key={m} value={m}>{m}월</option>)}</select>}<span className="ml-auto text-xs font-semibold text-blue-600">{range.start} ~ {range.end}</span></section>}
    {message && <div className="rounded-xl bg-blue-50 p-3 text-sm font-semibold text-blue-700">{message}</div>}{loading && <div className="p-10 text-center text-sm text-slate-400">불러오는 중…</div>}

    {!loading && tab === "records" && <><section className="flex flex-col gap-2 rounded-2xl border border-slate-200 bg-white p-4 md:flex-row"><div className="flex flex-wrap gap-1">{[["all","전체"],...types.map(([k,l]) => [k,l])] .map(([k,l]) => <button key={k} onClick={() => setType(k)} className={`rounded-full px-3 py-1.5 text-xs font-bold ${type === k ? "bg-slate-800 text-white" : "bg-slate-100 text-slate-500"}`}>{l}</button>)}</div><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="내용·직원 검색" className="ml-auto min-w-64 rounded-xl border border-slate-200 px-4 py-2 text-sm" /></section><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{entries.map((e) => { const open = expanded === e.id; return <article key={e.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><span className="rounded-lg bg-slate-100 px-2 py-1 text-xs font-bold text-slate-600">{e.icon} {e.label}</span><span className="text-xs text-slate-400">{e.week}</span></div><div className="mt-3 text-sm font-bold text-slate-800">{e.author}</div><div className={`mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-600 ${open ? "" : "line-clamp-4"}`}>{e.text}</div><button onClick={() => setExpanded(open ? "" : e.id)} className="mt-3 text-xs font-bold text-blue-600">{open ? "접기" : "전체 보기"}</button></article>; })}{!entries.length && <div className="col-span-full rounded-2xl bg-white p-12 text-center text-sm text-slate-400">선택한 기간의 성장기록이 없습니다.</div>}</div></>}

    {!loading && tab === "plan" && <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h3 className="text-xl font-bold">{year}년 {quarter}분기 레벨업계획</h3><p className="text-xs text-slate-400">목표와 월별 실행 결과를 한곳에서 관리합니다.</p></div><button disabled={!person} onClick={addGoal} className="rounded-xl bg-slate-800 px-4 py-2 text-sm font-bold text-white disabled:opacity-40">+ 목표 추가</button></div>{!person && <div className="mt-8 text-center text-sm text-amber-600">작성할 직원을 선택하세요.</div>}<div className="mt-5 space-y-4">{plan.goals.map((g, i) => <div key={g.id} className="rounded-2xl border border-slate-200 p-4"><div className="grid gap-2 lg:grid-cols-[40px_120px_1fr_90px_90px_120px_80px_36px]"><span className="py-2 text-center text-sm font-bold text-slate-300">{i+1}</span><select value={g.category} onChange={(e) => setGoal(g.id,{category:e.target.value})} className="rounded-lg border border-slate-200 px-2 text-sm">{[...GOLDEN_CATEGORIES,"기타"].map((c)=><option key={c}>{c}</option>)}</select><input value={g.title} onChange={(e)=>setGoal(g.id,{title:e.target.value})} placeholder="목표와 실행기준" className="rounded-lg border border-slate-200 px-3 py-2 text-sm"/><input value={g.currentLevel} onChange={(e)=>setGoal(g.id,{currentLevel:e.target.value})} placeholder="현재레벨" className="rounded-lg border border-slate-200 px-2 text-sm"/><input value={g.targetLevel} onChange={(e)=>setGoal(g.id,{targetLevel:e.target.value})} placeholder="목표레벨" className="rounded-lg border border-slate-200 px-2 text-sm"/><input value={g.budget} onChange={(e)=>setGoal(g.id,{budget:e.target.value})} placeholder="요청예산" className="rounded-lg border border-slate-200 px-2 text-sm"/><input type="number" min="0" max="100" value={g.progress||""} onChange={(e)=>setGoal(g.id,{progress:Number(e.target.value)||0})} placeholder="진도%" className="rounded-lg border border-slate-200 px-2 text-sm"/><button onClick={()=>setPlan({...plan,goals:plan.goals.filter((x)=>x.id!==g.id)})} className="text-slate-300 hover:text-rose-500">✕</button></div><div className="mt-3 grid gap-3 md:grid-cols-3">{[1,2,3].map((m)=><label key={m} className="text-xs font-bold text-slate-500">{(quarter-1)*3+m}월 결과<textarea value={g[`month${m}` as "month1"]} onChange={(e)=>setGoal(g.id,{[`month${m}`]:e.target.value})} rows={5} className="mt-1 w-full resize-y rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm font-normal leading-relaxed"/></label>)}</div></div>)}</div>{person&&<button onClick={savePlan} className="mt-5 w-full rounded-xl bg-[#172033] py-3 text-sm font-bold text-white">레벨업계획 저장</button>}</section>}

    {!loading && tab === "golden" && <div className="grid gap-6 xl:grid-cols-[360px_1fr]"><aside className="h-fit rounded-2xl border border-slate-200 bg-white p-4 shadow-sm xl:sticky xl:top-5"><h3 className="font-bold text-slate-900">분기 근거자료</h3><p className="mt-1 text-xs text-slate-400">주간 기록 {entries.filter((e)=>!person||e.author===person).length}건</p><div className="mt-3 max-h-[65vh] space-y-2 overflow-y-auto">{entries.filter((e)=>!person||e.author===person).map((e)=><div key={e.id} className="rounded-xl bg-slate-50 p-3"><div className="text-[10px] font-bold text-slate-400">{e.week} · {e.label}</div><div className="mt-1 line-clamp-4 whitespace-pre-wrap text-xs leading-5 text-slate-600">{e.text}</div></div>)}</div></aside><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div><h3 className="text-xl font-bold">{year}년 {quarter}분기 골든미팅카드</h3><p className="text-xs text-slate-400">왼쪽의 주간 근거자료를 보며 작성하세요.</p></div><div className="mt-4 grid grid-cols-2 gap-2 lg:grid-cols-4">{GOLDEN_QUESTIONS.map((q,i)=><button key={q} onClick={()=>setQuestion(i)} className={`rounded-xl px-3 py-3 text-xs font-bold ${question===i?"bg-slate-800 text-white":"bg-slate-100 text-slate-500"}`}>{q}</button>)}</div><div className="mt-5"><h4 className="text-lg font-bold text-slate-800">{GOLDEN_QUESTIONS[question]}</h4><div className="mt-3 grid gap-4 md:grid-cols-2">{GOLDEN_CATEGORIES.map((cat)=><label key={cat} className="text-xs font-bold text-slate-500">{cat}<textarea value={answer(GOLDEN_QUESTIONS[question],cat)} onChange={(e)=>setAnswer(GOLDEN_QUESTIONS[question],cat,e.target.value)} rows={8} className="mt-1 w-full resize-y rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm font-normal leading-relaxed outline-none focus:border-slate-400 focus:bg-white"/></label>)}</div></div>{person&&<button onClick={saveCard} className="mt-5 w-full rounded-xl bg-[#172033] py-3 text-sm font-bold text-white">골든미팅카드 저장</button>}</section></div>}
  </div>;
}
